name: Update sitemap <lastmod>

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.html"
      - "sitemap.xml"
  workflow_dispatch: {}
  schedule:
    - cron: "17 3 * * *"   # optional daily refresh (03:17 UTC)

permissions:
  contents: write

jobs:
  update-lastmod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Force-update <lastmod> for ALL urls
        run: |
          set -e
          python3 - << 'PY'
import os, datetime, xml.etree.ElementTree as ET
SP = "sitemap.xml"
if not os.path.exists(SP):
    print("No sitemap.xml found. Skipping."); raise SystemExit(0)

tree = ET.parse(SP)
root = tree.getroot()
ns = {"sm":"http://www.sitemaps.org/schemas/sitemap/0.9"}
ET.register_namespace("", ns["sm"])

now = datetime.datetime.utcnow().replace(microsecond=0).isoformat()+"Z"
count = 0
for url in root.findall("sm:url", ns):
    last = url.find("sm:lastmod", ns)
    if last is None:
        last = ET.SubElement(url, "{http://www.sitemaps.org/schemas/sitemap/0.9}lastmod")
    last.text = now
    count += 1

tree.write(SP, encoding="utf-8", xml_declaration=True)
print(f"Updated lastmod for {count} URL(s) to {now}.")
PY

      - name: Commit and push sitemap update
        run: |
          set -e
          if git status --porcelain | grep -q "sitemap.xml"; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add sitemap.xml
            git commit -m "chore(sitemap): force-update <lastmod>"
            git push
          else
            echo "No sitemap changes to commit."
          fi
