name: "Update sitemap <lastmod>"

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.html"
      - "sitemap.xml"
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * *"   # optional: daily

permissions:
  contents: write

jobs:
  update-lastmod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # need git history for last commit dates

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependency
        run: |
          npm init -y >/dev/null 2>&1
          npm i fast-xml-parser@4

      - name: Run lastmod updater
        run: node scripts/update-lastmod.js

      - name: Commit & push if sitemap changed
        run: |
          if ! git diff --quiet sitemap.xml; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add sitemap.xml
            git commit -m "chore: auto-update <lastmod> in sitemap.xml [skip ci]"
            git push
          else
            echo "No changes to commit, sitemap is current."
          fi
