name: Update sitemap <lastmod>

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.html"
      - "sitemap.xml"
      - "docs/sitemap.xml"
  workflow_dispatch: {}
  schedule:
    - cron: "17 3 * * *"   # optional daily refresh (03:17 UTC)

permissions:
  contents: write
  pull-requests: write   # IMPORTANT for PR mode

jobs:
  update-lastmod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Detect sitemap path
        id: detect
        shell: bash
        run: |
          set -e
          if [ -f "docs/sitemap.xml" ]; then
            echo "sp=docs/sitemap.xml" >> $GITHUB_OUTPUT
            echo "Using docs/sitemap.xml"
          elif [ -f "sitemap.xml" ]; then
            echo "sp=sitemap.xml" >> $GITHUB_OUTPUT
            echo "Using sitemap.xml"
          else
            echo "No sitemap.xml found at root or docs/. Exiting."
            exit 0

      - name: Update <lastmod> for ALL urls
        env:
          SP: ${{ steps.detect.outputs.sp }}
        run: |
          set -e
          python3 - << 'PY'
import os, datetime, xml.etree.ElementTree as ET
sp = os.environ.get("SP","sitemap.xml")
if not os.path.exists(sp):
  print(f"No sitemap at {sp}."); raise SystemExit(0)

tree = ET.parse(sp)
root = tree.getroot()
ns = {"sm":"http://www.sitemaps.org/schemas/sitemap/0.9"}
ET.register_namespace("", ns["sm"])

now = datetime.datetime.utcnow().replace(microsecond=0).isoformat()+"Z"
for url in root.findall("sm:url", ns):
  last = url.find("sm:lastmod", ns)
  if last is None:
    last = ET.SubElement(url, "{http://www.sitemaps.org/schemas/sitemap/0.9}lastmod")
  last.text = now

tree.write(sp, encoding="utf-8", xml_declaration=True)
print(f"Updated {sp} with lastmod = {now}.")
PY

      - name: Create PR for sitemap update
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore(sitemap): update <lastmod>'
          title: 'chore(sitemap): update <lastmod>'
          body: 'Automated sitemap <lastmod> refresh.'
          branch: ci/sitemap-lastmod
          delete-branch: true
