name: Update sitemap <lastmod>

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.html"
      - "sitemap.xml"
  workflow_dispatch: {}
  schedule:
    - cron: "17 3 * * *"   # optional daily refresh (03:17 UTC)

permissions:
  contents: write

jobs:
  update-lastmod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Force-update <lastmod> for ALL urls
        run: |
          set -e
          python3 - << 'PY'
import datetime, os, xml.etree.ElementTree as ET
sitemap_path = "sitemap.xml"
if not os.path.exists(sitemap_path):
    print("No sitemap.xml found. Skipping.")
    raise SystemExit(0)

tree = ET.parse(sitemap_path)
root = tree.getroot()
ns = {"sm": "http://www.sitemaps.org/schemas/sitemap/0.9"}
ET.register_namespace("", ns["sm"])

now_iso = datetime.datetime.utcnow().replace(microsecond=0).isoformat()+"Z"
count = 0
for url in root.findall("sm:url", ns):
    lastmod = url.find("sm:lastmod", ns)
    if lastmod is None:
        lastmod = ET.SubElement(url, "{http://www.sitemaps.org/schemas/sitemap/0.9}lastmod")
    lastmod.text = now_iso
    count += 1

tree.write(sitemap_path, encoding="utf-8", xml_declaration=True)
print(f"Updated lastmod for {count} url(s) to {now_iso}.")
PY

      # Create a PR instead of pushing directly (safe with protected main)
      - name: Create PR for sitemap update
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore(sitemap): force-update <lastmod>'
          title: 'chore(sitemap): force-update <lastmod>'
          body: 'Automated sitemap <lastmod> refresh for all URLs.'
          branch: ci/sitemap-lastmod
          delete-branch: true
