name: Generate sitemap

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Generate sitemap automatically
      - name: Generate sitemap.xml
        uses: cicirello/generate-sitemap@v1
        with:
          base-url: https://giftcardzoneeu.com
          path-to-root: .

          exclude: |
            /404.html
            /congrats/
            /neutral/
            /country/global/

      # Auto commit sitemap changes
      - name: Commit sitemap.xml
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto update sitemap"
          file_pattern: sitemap.xml

      # Notify search engines
      - name: Notify Search Engines
        run: |
          echo "Submitting sitemap..."

          curl -X GET "https://www.bing.com/ping?sitemap=https://giftcardzoneeu.com/sitemap.xml"

          curl -X GET "https://yandex.com/ping?sitemap=https://giftcardzoneeu.com/sitemap.xml"

          echo "Done."
